### PR TITLE
observe event course_category_deleted

### PR DESCRIPTION
**Pull request by mserve**
Monitor the course_category_deleted event and delete the instances, update required Moodle version

### CODE REVIEW

**Comment by mserve** [comment]
Remark: there should also be a test on deleting the category, I only tested manually yet

**Comment by mserve** [comment]
Tests added 👍🏻

**Comment by mserve** [comment]
Found an issue within local_cohortrole_render_add_buttons() when adding the plugin to our local testing installation, will check on it later:

Debug-Info:  

    SELECT id,parent FROM {course_categories} WHERE id = ?
    [array (
    0 => 1,
    )]
    Error code: invalidrecord 

Stack trace: 

    line 1599 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
    line 1575 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
    line 6732 of /lib/accesslib.php: call to moodle_database->get_record()
    line 126 of /local/cohortrole/locallib.php: call to context_coursecat::instance()
    line 141 of /local/cohortrole/locallib.php: call to local_cohortrole_get_context()
    line 162 of /local/cohortrole/locallib.php: call to local_cohortrole_get_context_name()
    line 37 of /local/cohortrole/index.php: call to local_cohortrole_render_add_buttons()

**Comment by mserve** [comment]
So, I found a way around using the issue depending on a category with id "1" by using the default category's context to obtain the roles. 

I noted a glitch on the form as it lost the "$mode" after validation, this is also fixed and found a bug in the sort order of the table. Additionally, one was able to assign course-category level only roles to the system context by not choosing any role 

One might discuss if the UI changes I introduced are useful. In our case, we have some categories having the same name in different top-level categories and it would be quite useful to see the full path. Also, the direct links to the roles and categories are more or less useful from a (i.e. my ....) admin perspective handling many roles and categories.

I did not squash the commits yet but could do so to keep the history a bit cleaner :)

**Comment by adpe** [comment]
> Monitor the course_category_deleted event and delete the instances, update required Moodle version

Thanks for implementing this missing part. For me we should not bump the version here yet. When the feature branch is done completely the `version.php` will be bumped at the end from the plugin maintainer.

Will review your stuff and push it to this merge request. Thanks for your hard work! So I'll clean up the history and remain you as the author.

Greets
Adrian

**Comment by adpe** [comment]
> Found an issue within local_cohortrole_render_add_buttons() when adding the plugin to our local testing installation, will check on it later:
> 
> Debug-Info:
> 
> ```
> SELECT id,parent FROM {course_categories} WHERE id = ?
> [array (
> 0 => 1,
> )]
> Error code: invalidrecord 
> ```
> 
> Stack trace:
> 
> ```
> line 1599 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
> line 1575 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
> line 6732 of /lib/accesslib.php: call to moodle_database->get_record()
> line 126 of /local/cohortrole/locallib.php: call to context_coursecat::instance()
> line 141 of /local/cohortrole/locallib.php: call to local_cohortrole_get_context()
> line 162 of /local/cohortrole/locallib.php: call to local_cohortrole_get_context_name()
> line 37 of /local/cohortrole/index.php: call to local_cohortrole_render_add_buttons()
> ```

Thanks for raising this new introduced issue. Can you please raise an own issue for that part? We'll only handle/merge the course category deletion handling in this PR.

Greets
Adrian

**Comment by uchida-nunet** [comment]
Very helpful. Thanks to both of you.

**Pull request closed without merging**
